#!/usr/bin/env python3
"""
Compile-time string encryption for SPECTER implant.

Scans C source files for ENCRYPTED_STRING("...") macros and generates
a header file with encrypted byte arrays using a random per-build 32-byte
XOR key.

Usage:
    python encrypt_strings.py <src_dir> <output_header>

The output header defines:
    - A random 32-byte XOR key (first 32 bytes of each blob)
    - Encrypted byte arrays for each string
    - ENCRYPTED_STRING macro that references the generated arrays

Decryption at runtime via spec_decrypt_string():
    key = blob[0..32], plaintext[i] = blob[i+32] ^ key[i % 32]
"""

import os
import re
import secrets
import sys


MACRO_PATTERN = re.compile(r'ENCRYPTED_STRING\(\s*"([^"]*?)"\s*\)')


XOR_KEY_SIZE = 32


def encrypt_string(plaintext: str, xor_key: list[int]) -> list[int]:
    """Encrypt a string: [key_0..key_31, encrypted_byte_0, encrypted_byte_1, ...]

    The 32-byte key is prepended, followed by the encrypted bytes where:
        enc[i] = plain[i] ^ key[i % 32]
    """
    assert len(xor_key) == XOR_KEY_SIZE
    encoded = plaintext.encode("ascii")
    blob = list(xor_key)  # 32-byte key prefix
    for i, b in enumerate(encoded):
        blob.append(b ^ xor_key[i % XOR_KEY_SIZE])
    return blob


def scan_sources(src_dir: str) -> dict[str, str]:
    """Scan .c and .h files for ENCRYPTED_STRING macros. Returns {string: var_name}."""
    strings = {}
    counter = 0

    for root, _dirs, files in os.walk(src_dir):
        for fname in sorted(files):
            if not (fname.endswith(".c") or fname.endswith(".h")):
                continue
            fpath = os.path.join(root, fname)
            with open(fpath, "r", encoding="utf-8", errors="ignore") as f:
                content = f.read()
            for match in MACRO_PATTERN.finditer(content):
                s = match.group(1)
                if s not in strings:
                    var_name = f"_enc_str_{counter}"
                    strings[s] = var_name
                    counter += 1

    return strings


def generate_header(strings: dict[str, str], xor_key: list[int]) -> str:
    """Generate the encrypted strings header file."""
    key_hex = " ".join(f"0x{b:02X}" for b in xor_key)
    lines = [
        "/**",
        " * SPECTER Implant — Encrypted Strings (auto-generated)",
        " *",
        " * Generated by encrypt_strings.py. Do not edit manually.",
        f" * XOR key ({XOR_KEY_SIZE} bytes): {key_hex}",
        " */",
        "",
        "#ifndef ENCRYPTED_STRINGS_H",
        "#define ENCRYPTED_STRINGS_H",
        "",
        '#include "specter.h"',
        "",
    ]

    for plaintext, var_name in sorted(strings.items(), key=lambda x: x[1]):
        blob = encrypt_string(plaintext, xor_key)
        byte_str = ", ".join(f"0x{b:02X}" for b in blob)
        lines.append(f"/* \"{plaintext}\" ({len(plaintext)} chars) */")
        lines.append(
            f"static const BYTE {var_name}[{len(blob)}] = {{ {byte_str} }};"
        )
        lines.append(
            f"#define {var_name.upper()}_LEN {len(blob)}"
        )
        lines.append("")

    # Generate a lookup macro
    lines.append("/*")
    lines.append(" * Usage: ENCRYPTED_STRING(\"literal\") expands to the variable name.")
    lines.append(" * At runtime, call spec_decrypt_string(var, var_LEN, output_buf).")
    lines.append(" */")
    lines.append("")
    lines.append("#endif /* ENCRYPTED_STRINGS_H */")
    lines.append("")

    return "\n".join(lines)


def main():
    if len(sys.argv) < 3:
        print("Usage: encrypt_strings.py <src_dir> <output_header>")
        print("  src_dir       — directory to scan for ENCRYPTED_STRING macros")
        print("  output_header — path to write the generated header")
        sys.exit(1)

    src_dir = sys.argv[1]
    output_path = sys.argv[2]

    if not os.path.isdir(src_dir):
        print(f"[!] Source directory not found: {src_dir}")
        sys.exit(1)

    strings = scan_sources(src_dir)

    if not strings:
        print("[*] No ENCRYPTED_STRING macros found. Generating empty header.")

    # Generate a 32-byte random XOR key (no zero bytes to avoid null issues)
    xor_key = [secrets.randbelow(255) + 1 for _ in range(XOR_KEY_SIZE)]
    header = generate_header(strings, xor_key)

    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(header)

    key_hex = " ".join(f"0x{b:02X}" for b in xor_key[:4])
    print(f"[+] Generated encrypted strings header: {output_path}")
    print(f"    Strings encrypted: {len(strings)}")
    print(f"    XOR key ({XOR_KEY_SIZE} bytes): {key_hex} ...")


if __name__ == "__main__":
    main()
