/// <reference lib="webworker" />

// ──────────────────────────────────────────────────────────────────────
// SPECTER C2 — Service Worker
//
// Provides offline support: caches static assets, stores session data
// in IndexedDB, queues tasks offline, and syncs on reconnect.
// Uses Workbox precaching (injected by vite-plugin-pwa) for static
// assets, plus custom fetch handling for gRPC-Web requests.
// ──────────────────────────────────────────────────────────────────────

import { precacheAndRoute } from 'workbox-precaching'

declare const self: ServiceWorkerGlobalScope;

// Precache static assets generated by vite-plugin-pwa
precacheAndRoute(self.__WB_MANIFEST);

const CACHE_NAME = 'specter-v1';
// Kept for runtime caching of dynamic requests; static precaching is handled by Workbox above.

// IndexedDB database name and stores
const DB_NAME = 'specter-offline';
const DB_VERSION = 1;
const STORE_SESSIONS = 'sessions';
const STORE_TASK_QUEUE = 'taskQueue';

// ── IndexedDB helpers ───────────────────────────────────────────────

function openDB(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    const req = indexedDB.open(DB_NAME, DB_VERSION);

    req.onupgradeneeded = () => {
      const db = req.result;
      if (!db.objectStoreNames.contains(STORE_SESSIONS)) {
        db.createObjectStore(STORE_SESSIONS, { keyPath: 'session_id' });
      }
      if (!db.objectStoreNames.contains(STORE_TASK_QUEUE)) {
        db.createObjectStore(STORE_TASK_QUEUE, { keyPath: 'id', autoIncrement: true });
      }
    };

    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error);
  });
}

function idbPut(storeName: string, data: unknown): Promise<void> {
  return openDB().then(
    (db) =>
      new Promise((resolve, reject) => {
        const tx = db.transaction(storeName, 'readwrite');
        tx.objectStore(storeName).put(data);
        tx.oncomplete = () => resolve();
        tx.onerror = () => reject(tx.error);
      }),
  );
}

function idbGetAll<T>(storeName: string): Promise<T[]> {
  return openDB().then(
    (db) =>
      new Promise((resolve, reject) => {
        const tx = db.transaction(storeName, 'readonly');
        const req = tx.objectStore(storeName).getAll();
        req.onsuccess = () => resolve(req.result as T[]);
        req.onerror = () => reject(req.error);
      }),
  );
}

function idbClear(storeName: string): Promise<void> {
  return openDB().then(
    (db) =>
      new Promise((resolve, reject) => {
        const tx = db.transaction(storeName, 'readwrite');
        tx.objectStore(storeName).clear();
        tx.oncomplete = () => resolve();
        tx.onerror = () => reject(tx.error);
      }),
  );
}

// ── Install ─────────────────────────────────────────────────────────

self.addEventListener('install', (_event: ExtendableEvent) => {
  // Static asset precaching is handled by Workbox (precacheAndRoute above).
  // Activate immediately without waiting for old SW to be released.
  self.skipWaiting();
});

// ── Activate ────────────────────────────────────────────────────────

self.addEventListener('activate', (event: ExtendableEvent) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          keys
            .filter((key) => key !== CACHE_NAME)
            .map((key) => caches.delete(key)),
        ),
      )
      .then(() => self.clients.claim()),
  );
});

// ── Fetch ───────────────────────────────────────────────────────────

self.addEventListener('fetch', (event: FetchEvent) => {
  const { request } = event;
  const url = new URL(request.url);

  // gRPC-Web requests — network first, queue if offline
  if (url.pathname.startsWith('/specter.v1')) {
    event.respondWith(handleGrpcRequest(request));
    return;
  }

  // Static assets — cache first, then network
  event.respondWith(
    caches.match(request).then((cached) => {
      if (cached) return cached;

      return fetch(request).then((response) => {
        // Cache successful GET responses for static assets
        if (request.method === 'GET' && response.status === 200) {
          const clone = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(request, clone));
        }
        return response;
      });
    }).catch(() => {
      // Offline fallback for navigation requests
      if (request.mode === 'navigate') {
        return caches.match('/ui/index.html') as Promise<Response>;
      }
      return new Response('Offline', { status: 503 });
    }),
  );
});

// ── gRPC request handling ───────────────────────────────────────────

async function handleGrpcRequest(request: Request): Promise<Response> {
  try {
    const response = await fetch(request);

    // Cache session list responses in IndexedDB for offline viewing
    if (request.url.includes('ListSessions') && response.ok) {
      const clone = response.clone();
      try {
        const data = await clone.json();
        if (data.sessions) {
          for (const session of data.sessions) {
            await idbPut(STORE_SESSIONS, session);
          }
        }
      } catch {
        // Not JSON or parse error — skip caching
      }
    }

    return response;
  } catch {
    // Offline — check if this is a task queue request
    if (request.url.includes('QueueTask')) {
      try {
        const body = await request.clone().json();
        await idbPut(STORE_TASK_QUEUE, {
          ...body,
          queued_at: new Date().toISOString(),
        });
        return new Response(
          JSON.stringify({ status: 'queued_offline' }),
          {
            status: 202,
            headers: { 'Content-Type': 'application/json' },
          },
        );
      } catch {
        // Fall through to offline error
      }
    }

    // Return cached session data if available
    if (request.url.includes('ListSessions')) {
      const sessions = await idbGetAll(STORE_SESSIONS);
      if (sessions.length > 0) {
        return new Response(
          JSON.stringify({ sessions, _offline: true }),
          {
            status: 200,
            headers: { 'Content-Type': 'application/json' },
          },
        );
      }
    }

    return new Response(
      JSON.stringify({ error: 'offline' }),
      { status: 503, headers: { 'Content-Type': 'application/json' } },
    );
  }
}

// ── Sync queued tasks on reconnect ──────────────────────────────────

self.addEventListener('message', (event: ExtendableMessageEvent) => {
  if (event.data?.type === 'SYNC_TASKS') {
    event.waitUntil(syncQueuedTasks());
  }
});

interface QueuedTask {
  id: number;
  session_id: string;
  task_type: string;
  arguments: string;
  queued_at: string;
}

async function syncQueuedTasks(): Promise<void> {
  const tasks = await idbGetAll<QueuedTask>(STORE_TASK_QUEUE);
  if (tasks.length === 0) return;

  const results: Array<{ task: QueuedTask; success: boolean }> = [];

  for (const task of tasks) {
    try {
      const response = await fetch('/specter.v1.SpecterService/QueueTask', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          session_id: task.session_id,
          task_type: task.task_type,
          arguments: task.arguments,
        }),
      });
      results.push({ task, success: response.ok });
    } catch {
      results.push({ task, success: false });
    }
  }

  // Clear successfully synced tasks
  const allSynced = results.every((r) => r.success);
  if (allSynced) {
    await idbClear(STORE_TASK_QUEUE);
  }

  // Notify clients
  const clients = await self.clients.matchAll();
  for (const client of clients) {
    client.postMessage({
      type: 'SYNC_COMPLETE',
      total: tasks.length,
      synced: results.filter((r) => r.success).length,
    });
  }
}
